[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.0"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  branch = "vincent/memory-leak"
  source = "github.com/irisnet/tendermint"

[prune]
  go-tests = true
  unused-packages = true
